version: '3.8'

services:
  insurance-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
      - UPLOAD_DIRECTORY=/app/uploads
      - MAX_FILE_SIZE_MB=50
      - ALLOWED_EXTENSIONS=pdf
    volumes:
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s